"""add content_template and template_data to slides

Revision ID: a239ce4260fd
Revises: 7a1dff803cc2
Create Date: 2026-02-27 23:15:49.995245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a239ce4260fd'
down_revision: Union[str, None] = '7a1dff803cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('content_template', sa.String(length=20), server_default='text', nullable=False))
    op.add_column('slides', sa.Column('template_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slides', 'template_data')
    op.drop_column('slides', 'content_template')
    # ### end Alembic commands ###
